// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using project_be;

#nullable disable

namespace project_be.Migrations
{
    [DbContext(typeof(ProjectDbContext))]
    partial class ProjectDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("project_be.Models.AddressModel", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("CountryName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Address");

                    b.HasData(
                        new
                        {
                            Id = "AR",
                            CountryName = "Argentina"
                        },
                        new
                        {
                            Id = "MX",
                            CountryName = "Mexico"
                        },
                        new
                        {
                            Id = "BR",
                            CountryName = "Brazil"
                        },
                        new
                        {
                            Id = "AU",
                            CountryName = "Australia"
                        },
                        new
                        {
                            Id = "HR",
                            CountryName = "Croatia"
                        },
                        new
                        {
                            Id = "FR",
                            CountryName = "France"
                        });
                });

            modelBuilder.Entity("project_be.Models.ProjectModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CountryId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProjectName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.ToTable("Project");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CountryId = "AR",
                            ProjectName = "Project 1"
                        },
                        new
                        {
                            Id = 2,
                            CountryId = "MX",
                            ProjectName = "Project 2"
                        },
                        new
                        {
                            Id = 3,
                            CountryId = "BR",
                            ProjectName = "Project 3"
                        },
                        new
                        {
                            Id = 4,
                            CountryId = "AU",
                            ProjectName = "Project 4"
                        },
                        new
                        {
                            Id = 5,
                            CountryId = "HR",
                            ProjectName = "Project 5"
                        },
                        new
                        {
                            Id = 6,
                            CountryId = "FR",
                            ProjectName = "Project 6"
                        },
                        new
                        {
                            Id = 16,
                            CountryId = "AR",
                            ProjectName = "Project 7"
                        },
                        new
                        {
                            Id = 7,
                            CountryId = "MX",
                            ProjectName = "Project 8"
                        },
                        new
                        {
                            Id = 8,
                            CountryId = "BR",
                            ProjectName = "Project 9"
                        },
                        new
                        {
                            Id = 9,
                            CountryId = "AU",
                            ProjectName = "Project 10"
                        },
                        new
                        {
                            Id = 10,
                            CountryId = "HR",
                            ProjectName = "Project 11"
                        },
                        new
                        {
                            Id = 11,
                            CountryId = "FR",
                            ProjectName = "Project 12"
                        },
                        new
                        {
                            Id = 12,
                            CountryId = "AR",
                            ProjectName = "Project 13"
                        },
                        new
                        {
                            Id = 13,
                            CountryId = "MX",
                            ProjectName = "Project 14"
                        },
                        new
                        {
                            Id = 14,
                            CountryId = "BR",
                            ProjectName = "Project 15"
                        },
                        new
                        {
                            Id = 15,
                            CountryId = "AU",
                            ProjectName = "Project 16"
                        });
                });

            modelBuilder.Entity("project_be.Models.ProjectModel", b =>
                {
                    b.HasOne("project_be.Models.AddressModel", "Country")
                        .WithMany()
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");
                });
#pragma warning restore 612, 618
        }
    }
}
